### PR TITLE
Organizing project

### PR DESCRIPTION
**Pull request by fave77**

### CODE REVIEW

**Comment by fave77** [comment]
Before merging, please verify the relevant files are in exact place for the purpose of making this pull request is make the **_master_** branch look like _**organizing_project**_

**Comment by fave77** [comment]
Before merging any other request please do consider merging this one before as it can have conflict again!

**Comment by fave77** [comment]
Nimmo, please check out my repo before merging it!

**Comment by Nimmo1993** [comment]
:)

**Pull request merged**
